/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTFResult } from "./types";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("./model/car.glb") as GLTFResult;
  materials["BackLighs"].envMapIntensity = 0.5;
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          userData={{ name: "Sketchfab_model" }}
        >
          <group name="root" userData={{ name: "root" }}>
            <group
              name="GLTF_SceneRootNode"
              rotation={[Math.PI / 2, 0, 0]}
              userData={{ name: "GLTF_SceneRootNode" }}
            >
              <group
                name="Cylinder_5"
                position={[0, 2.039, 0]}
                scale={[1, 0.341, 1]}
                userData={{ name: "Cylinder_5" }}
              />
              <group
                name="Plane_7"
                position={[0, -0.034, 0]}
                scale={11.675}
                userData={{ name: "Plane_7" }}
              />
              <group
                name="RR_4"
                position={[-1.231, -0.039, -2.048]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.001}
                userData={{ name: "RR_4" }}
              >
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials["wire_135006006.001"]}
                  userData={{ name: "Object_42" }}
                />
                <mesh
                  name="Object_43"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_43.geometry}
                  material={materials["wire_162162162.001"]}
                  userData={{ name: "Object_43" }}
                />
              </group>
              <group
                name="senna_3"
                position={[0, 0.402, 0]}
                userData={{ name: "senna_3" }}
              >
                <group
                  name="FL_0"
                  position={[1.18, 0.062, 1.651]}
                  rotation={[Math.PI / 2, 0, -Math.PI]}
                  scale={0.001}
                  userData={{ name: "FL_0" }}
                >
                  <mesh
                    name="Object_33"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_33.geometry}
                    material={materials["wire_135006006.002"]}
                    userData={{ name: "Object_33" }}
                  />
                  <mesh
                    name="Object_34"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_34.geometry}
                    material={materials["wire_162162162.002"]}
                    userData={{ name: "Object_34" }}
                  />
                </group>
                <group
                  name="FR_1"
                  position={[-1.195, -0.44, 1.664]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.001}
                  userData={{ name: "FR_1" }}
                >
                  <mesh
                    name="Object_36"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_36.geometry}
                    material={materials.wire_135006006}
                    userData={{ name: "Object_36" }}
                  />
                  <mesh
                    name="Object_37"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_37.geometry}
                    material={materials.wire_162162162}
                    userData={{ name: "Object_37" }}
                  />
                </group>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.BodyPaint}
                  userData={{ name: "Object_10" }}
                />
                <mesh
                  name="Object_11"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials.BodyPaint}
                  userData={{ name: "Object_11" }}
                />
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.OrangeBody}
                  userData={{ name: "Object_12" }}
                />
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials.BlackMetallic}
                  userData={{ name: "Object_13" }}
                />
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.BlackMetallic}
                  userData={{ name: "Object_14" }}
                />
                <mesh
                  name="Object_15"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_15.geometry}
                  material={materials.BlackMetallic}
                  userData={{ name: "Object_15" }}
                />
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.Windows}
                  userData={{ name: "Object_16" }}
                />
                <mesh
                  name="Object_17"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_17.geometry}
                  userData={{ name: "Object_17" }}
                >
                  <meshBasicMaterial
                    toneMapped={false}
                    color={new THREE.Color("#ffd242").multiplyScalar(10)}
                  />
                </mesh>
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.material}
                  userData={{ name: "Object_18" }}
                />
                <mesh
                  name="Object_19"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials.BackLighs}
                  userData={{ name: "Object_19" }}
                />
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.Baclight}
                  userData={{ name: "Object_20" }}
                />
                <mesh
                  name="Object_21"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_21.geometry}
                  material={materials.Shining}
                  userData={{ name: "Object_21" }}
                />
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.Back_Plate}
                  userData={{ name: "Object_22" }}
                />
                <mesh
                  name="Object_23"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials.Dashboard}
                  userData={{ name: "Object_23" }}
                />
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.Red_Light}
                  userData={{ name: "Object_24" }}
                />
                <mesh
                  name="Object_25"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials.Metallic}
                  userData={{ name: "Object_25" }}
                />
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials.Seat_lining}
                  userData={{ name: "Object_26" }}
                />
                <mesh
                  name="Object_27"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_27.geometry}
                  material={materials.Seat}
                  userData={{ name: "Object_27" }}
                />
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials.screen}
                  userData={{ name: "Object_28" }}
                />
                <mesh
                  name="Object_29"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_29.geometry}
                  material={materials.Crbon}
                  userData={{ name: "Object_29" }}
                />
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.Interior}
                  userData={{ name: "Object_30" }}
                />
                <mesh
                  name="Object_31"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_31.geometry}
                  material={materials["Material.001"]}
                  userData={{ name: "Object_31" }}
                />
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.GreyBlack}
                  userData={{ name: "Object_4" }}
                />
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials.GreyBlack}
                  userData={{ name: "Object_5" }}
                />
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.GreyBlack}
                  userData={{ name: "Object_6" }}
                />
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials.Translucent}
                  userData={{ name: "Object_7" }}
                />
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.Grey}
                  userData={{ name: "Object_8" }}
                />
                <mesh
                  name="Object_9"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_9.geometry}
                  material={materials.Glass}
                  userData={{ name: "Object_9" }}
                />
                <group
                  name="RL_2"
                  position={[1.23, -0.44, -2.048]}
                  rotation={[Math.PI / 2, 0, Math.PI]}
                  scale={0.001}
                  userData={{ name: "RL_2" }}
                >
                  <mesh
                    name="Object_39"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_39.geometry}
                    material={materials["wire_135006006.003"]}
                    userData={{ name: "Object_39" }}
                  />
                  <mesh
                    name="Object_40"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_40.geometry}
                    material={materials["wire_162162162.003"]}
                    userData={{ name: "Object_40" }}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./model/car.glb");
